[build]
  base = "web"
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[edge_functions]]
  path = "/*"
  function = "csp-nonce"

# Explicit CSP for production on Netlify (overrides defaults)
# Note: Keep permissive for inline scripts required by Next runtime.
